# Generated by Django 4.1.7 on 2023-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeapp", "0007_product_productdetail_orderhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
