# Generated by Django 4.1.7 on 2023-03-04 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storeapp", "0008_user_phone_number_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderhistory",
            name="user",
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="buyer_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orderhistory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productdetail",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productdetail",
                to="storeapp.product",
            ),
        ),
    ]
