# Generated by Django 4.1.7 on 2023-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storeapp", "0014_product_seller_eth_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="eth_address",
            field=models.CharField(default="0x0000", max_length=100),
        ),
    ]
