# Generated by Django 4.1.7 on 2023-05-10 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("storeapp", "0015_alter_user_eth_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="eth_address",
            field=models.CharField(blank=True, default="0x0000", max_length=100),
        ),
        migrations.CreateModel(
            name="PasswordRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(default="", max_length=20, unique=True)),
                (
                    "originated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_recovery",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
